/** Real browser acceptance checks for the measured, local star atlas. */
import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const origin=process.env.COMPILEUNIVERSE_URL||'http://127.0.0.1:8781';
const artifacts=fileURLToPath(new URL('../artifacts/',import.meta.url));
const browser=await chromium.launch({headless:true});
const errors=[],report={};
const quantile=(a,q)=>[...a].sort((a,b)=>a-b)[Math.min(a.length-1,Math.floor(a.length*q))]||0;
async function ready(page){page.on('pageerror',e=>errors.push(e.message));await page.goto(origin);await page.waitForFunction(()=>window.__compiledAtlas?.ready&&__compiledAtlas.data.frame,{timeout:45000});}
async function nextFrame(page,fn,arg){const n=await page.evaluate(()=>__compiledAtlas.metrics.frames);if(fn)await page.evaluate(fn,arg);await page.waitForFunction(n=>__compiledAtlas.metrics.frames>n,n);}
try{
 const page=await browser.newPage({viewport:{width:1440,height:900}});let serverFrames=0;
 page.on('request',r=>{if(r.url().includes('/api/frame'))serverFrames++;});
 await ready(page);await page.waitForTimeout(700);
 assert.equal(await page.locator('#object-title').textContent(),'Earth');
 assert.equal(await page.evaluate(()=>__compiledAtlas.data.stats.catalog_stars),109401);
 const baseline=await page.evaluate(()=>({at:performance.now(),frames:__compiledAtlas.metrics.frames}));
 await page.waitForTimeout(2000);
 const measured=await page.evaluate(()=>({at:performance.now(),frames:__compiledAtlas.metrics.frames,metrics:__compiledAtlas.metrics,state:__compiledAtlas.state}));
 report.earth={fps:(measured.frames-baseline.frames)*1000/(measured.at-baseline.at),grid:[measured.state.cols,measured.state.rows],computeMedianMs:quantile(measured.metrics.computeTimes,.5),displayMedianMs:quantile(measured.metrics.displayTimes,.5)};
 await nextFrame(page,()=>__compiledAtlas.setPaused(true));await page.waitForTimeout(120);
 const paused=await page.evaluate(()=>({frames:__compiledAtlas.metrics.frames,time:__compiledAtlas.state.time}));
 await page.waitForTimeout(250);assert.deepEqual(await page.evaluate(()=>({frames:__compiledAtlas.metrics.frames,time:__compiledAtlas.state.time})),paused,'A stationary paused view must stop frame computation');
 await page.screenshot({path:`${artifacts}/atlas-earth-desktop.png`});
 await page.locator('#viewport').focus();const oldPosition=await page.evaluate(()=>[...__compiledAtlas.state.position]);
 await page.keyboard.down('ArrowRight');await page.waitForTimeout(250);await page.keyboard.up('ArrowRight');
 assert.notDeepEqual(await page.evaluate(()=>__compiledAtlas.state.position),oldPosition,'Orbit controls must work while scene time is paused');
 await nextFrame(page,()=>{__compiledAtlas.homeCamera();__compiledAtlas.setPaused(false);});
 const departure=await page.evaluate(()=>({at:performance.now(),frames:__compiledAtlas.metrics.frames,position:[...__compiledAtlas.state.position]}));
 await page.locator('#search-open').click();await page.locator('#star-search').fill('Alpha Centauri');await page.getByRole('button',{name:'Discover Alpha Centauri A',exact:true}).click();await page.locator('#fly-preview').click();await page.waitForFunction(()=>__compiledAtlas.journey);
 await page.waitForTimeout(5400);
 const halfway=await page.evaluate(()=>({position:[...__compiledAtlas.state.position],journey:__compiledAtlas.journey,stats:__compiledAtlas.data.stats}));
 assert.ok(Math.hypot(...halfway.position)>.05&&Math.hypot(...halfway.position)<1.32,'Journey must pass through real interstellar coordinates');
 await page.screenshot({path:`${artifacts}/atlas-journey.png`});
 await page.waitForFunction(()=>!__compiledAtlas.journey&&__compiledAtlas.selected.index===__compiledAtlas.destinations.alpha.index,{timeout:15000});
 await nextFrame(page);
 const arrived=await page.evaluate(()=>({at:performance.now(),frames:__compiledAtlas.metrics.frames,position:[...__compiledAtlas.state.position],target:__compiledAtlas.selected,stats:__compiledAtlas.data.stats,metrics:__compiledAtlas.metrics}));
 const offset=Math.hypot(...arrived.position.map((v,i)=>v-arrived.target.position[i]));
 assert.ok(Math.abs(offset/arrived.target.radius_pc-4.8)<.001,'Journey must arrive outside the correctly scaled target surface');
 assert.ok(arrived.stats.surface_cells>300,'The destination must resolve into character surface cells');
 report.journey={durationSeconds:(arrived.at-departure.at)/1000,fps:(arrived.frames-departure.frames)*1000/(arrived.at-departure.at),arrivalDistanceInRadii:offset/arrived.target.radius_pc,computeMedianMs:quantile(arrived.metrics.computeTimes,.5),frameP95Ms:quantile(arrived.metrics.frameIntervals,.95)};
 await page.screenshot({path:`${artifacts}/atlas-alpha-desktop.png`});
 await page.locator('#look-sun').click();await nextFrame(page);
 const back=await page.evaluate(()=>{const a=__compiledAtlas,s=a.state,f=[Math.sin(s.yaw)*Math.cos(s.pitch),Math.sin(s.pitch),Math.cos(s.yaw)*Math.cos(s.pitch)],d=s.position.map(x=>-x/Math.hypot(...s.position));return {position:s.position,selected:a.selected.index,alignment:f.reduce((x,v,i)=>x+v*d[i],0),mode:a.mode};});
 assert.deepEqual(back.position,arrived.position,'Looking back must not teleport the camera');assert.equal(back.selected,0);assert.ok(back.alignment>1-1e-10);
 await page.screenshot({path:`${artifacts}/atlas-looking-home.png`});
 await page.locator('#search-open').click();await page.locator('#star-search').fill('Proxima');
 assert.ok(await page.locator('#search-results .destination').count()>=2);
 await page.getByRole('button',{name:'Discover Proxima Centauri',exact:true}).click();await page.locator('#fly-preview').click();await page.waitForFunction(()=>__compiledAtlas.journey);await page.waitForTimeout(150);
 await page.locator('#cancel-journey').click();assert.equal(await page.evaluate(()=>__compiledAtlas.journey),null);assert.equal(await page.evaluate(()=>__compiledAtlas.mode),'free');
 await page.locator('#viewport').focus();const beforeFly=await page.evaluate(()=>[...__compiledAtlas.state.position]);
 await page.keyboard.down('KeyD');await page.waitForTimeout(150);await page.keyboard.up('KeyD');assert.notDeepEqual(await page.evaluate(()=>__compiledAtlas.state.position),beforeFly);
 await nextFrame(page,()=>__compiledAtlas.travelTo(__compiledAtlas.destinations.proxima,{instant:true}));
 await page.screenshot({path:`${artifacts}/atlas-proxima.png`});
 await page.locator('#info-open').click();await page.locator('#density').selectOption('160,70');await page.locator('#display-mode').selectOption('text');
 await page.waitForFunction(()=>document.querySelector('#textscreen').textContent.split('\n').length===70);
 await nextFrame(page,()=>__compiledAtlas.setPaused(true));
 assert.equal(await page.locator('#textscreen').isVisible(),true);assert.equal(await page.locator('#glyphscreen').isVisible(),false);
 const plainDownload=page.waitForEvent('download');await page.locator('#save-text').click();const plain=await plainDownload;const text=await readFile(await plain.path(),'utf8');
 assert.equal(plain.suggestedFilename(),'proxima-centauri.txt');assert.equal(text.split('\n').length,71);assert.ok(text.split('\n').slice(0,-1).every(row=>row.length===160));
 const ansiDownload=page.waitForEvent('download');await page.locator('#save-ansi').click();assert.ok((await readFile(await(await ansiDownload).path(),'utf8')).includes('\x1b[48;2;'));
 await page.locator('#display-mode').selectOption('accelerated');await page.locator('#density').selectOption('adaptive');await page.locator('#close-panel').click();
 await page.context().setOffline(true);
 await nextFrame(page,()=>{__compiledAtlas.travelTo(__compiledAtlas.destinations.sirius,{instant:true});__compiledAtlas.setPaused(false);});
 assert.equal(await page.evaluate(()=>__compiledAtlas.selected.name),'Sirius');assert.equal(serverFrames,0,'Atlas frames must stay local, including destination changes');
 await page.context().setOffline(false);report.offlineDestinationChange=true;report.serverFrameRequests=serverFrames;
 await page.close();
 const phone=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true,deviceScaleFactor:2,reducedMotion:'reduce'});await ready(phone);
 const mobile=await phone.evaluate(()=>({width:document.documentElement.scrollWidth,innerWidth,canvas:document.querySelector('#glyphscreen').getBoundingClientRect().toJSON(),grid:[__compiledAtlas.state.cols,__compiledAtlas.state.rows]}));
 assert.ok(mobile.width<=mobile.innerWidth);assert.ok(mobile.canvas.width>=380&&mobile.canvas.height>=825);
 await phone.screenshot({path:`${artifacts}/atlas-earth-mobile.png`});
 await phone.locator('#primary-journey').tap();await phone.waitForFunction(()=>__compiledAtlas.selected.id==='moon'&&!__compiledAtlas.journey);
 await nextFrame(phone);await phone.screenshot({path:`${artifacts}/atlas-moon-mobile.png`});
 await phone.locator('#info-open').tap();assert.equal(await phone.locator('#panel').isVisible(),true);await phone.locator('#close-panel').tap();
 report.mobile=mobile;report.errors=errors;assert.deepEqual(errors,[]);report.passed=true;
 console.log(JSON.stringify(report,null,2));
}finally{await browser.close();await writeFile(`${artifacts}/atlas-browser-validation.json`,JSON.stringify(report,null,2)+'\n');}
